pub mod clear_all;
pub mod find_or_allocate_entry;
pub mod get_entry;
pub mod init;
pub mod lookup;
pub mod number_of_active_entries;
pub mod remove_entry;
pub mod set_entry;
pub mod set_security_frame_counter;
